### ISSUE TITLE
Unarchive equivalent in v4

### ISSUE THREAD

**Issue by tomcruise81** [mholt/archiver#328] opened 2022-03-22 16:20 UTC
## What would you like to have changed?

A default `Unarchive` function that operates similarly to https://pkg.go.dev/github.com/mholt/archiver#Unarchive that either:
* Could be passed into `extractor.Extract(...)` as the `FileHandler function
* Or is it's own interface on a given `Format`

## Why is this feature a useful, necessary, and/or important addition to this project?

It would extend the feature set from v3 to v4, while still offering contextual awareness

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

1. Sticking with v3 / without contextual awareness
2. Implementing all the unachriving logic ourselves in a `FileHandler` function

**Comment by mholt** [comment] 2022-03-22 16:26
Thanks; this is a duplicate of #311. Feel free to continue discussion there!

**Closed by mholt** 2022-03-22 16:26 UTC
Labels: feature request

**Comment by tomcruise81** [comment] 2022-03-22 17:00
Sorry about that,
