### ISSUE TITLE
Symbolic links

### ISSUE THREAD

**Issue by gedw99** [mholt/archiver#108] opened 2018-11-09 15:53 UTC
Does it respect symbolic links ?
I had some issues before and today noticed that the Google GitHub org has a new golang package specifically for interacting with the file system on all platforms to respect symbolic links.

https://github.com/google/renameio

**Comment by mholt** [comment] 2018-11-09 16:38
Sort of, but I think this is a duplicate of:

#21
#31 
#74

Would love to have you jump in any of those issues and contribute patches! Thanks!

**Closed by mholt** 2018-11-09 16:38 UTC
