### ISSUE TITLE
Unable to decrypt 7-ZIP file with password (err: breader.ReadByte: no data!)

### ISSUE THREAD

**Issue by zollty** [mholt/archiver#376] opened 2023-04-05 12:23 UTC
## What version of the package or command are you using?
v4.0.0-alpha.7

## What are you trying to do?
Decompress 7-ZIP file with password

## What did you expect to happen, and what actually happened instead?
Err:  breader.ReadByte: no data !

After my testing:   

All 7-zip encrypted files created by  software [7-zip](https://www.7-zip.org) (official windows x64 version, default options)  cannot be decrypted.    

but files encrypted by another software [Bandzip ](https://en.bandisoft.com/) can be decrypted normally.

## What steps did you take?
see： https://github.com/bodgit/sevenzip/issues/75

**Comment by mholt** [comment] 2023-04-05 20:04
Duplicate of #375 ...

This isn't even a bug in archiver, it's something about the upstream repo which I see you opened 2 issues there as well. Please only open 1 issue.

**Closed by mholt** 2023-04-05 20:04 UTC
