### ISSUE TITLE
RFE: port to github.com/pierrec/lz4/v4

### ISSUE THREAD

**Issue by rathann** [mholt/archiver#248] opened 2020-10-05 11:51 UTC
## What would you like to have changed?
Make it possible to build with `github.com/pierrec/lz4/v4`.

## Why is this feature a useful, necessary, and/or important addition to this project?
`lz4` was updated to 4.0.2 in Fedora rawhide and `archiver` no longer builds using distribution-provided Go packages as a result.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
I'm forced to stop updating `archiver` until it's ported to `lz4` v4 API or someone creates a compatibility package with v3 API.

## Please link to any relevant issues, pull requests, or other discussions.

To see the issue, patch the source with the following patch:
``` diff
diff -up archiver-3.3.2/lz4.go.lz4 archiver-3.3.2/lz4.go
--- archiver-3.3.2/lz4.go.lz4	2020-09-28 10:43:21.000000000 +0200
+++ archiver-3.3.2/lz4.go	2020-10-05 13:06:07.879465436 +0200
@@ -5,7 +5,7 @@ import (
 	"io"
 	"path/filepath"
 
-	"github.com/pierrec/lz4/v3"
+	"github.com/pierrec/lz4"
 )
 
 // Lz4 facilitates LZ4 compression.
diff -up archiver-3.3.2/tarlz4.go.lz4 archiver-3.3.2/tarlz4.go
--- archiver-3.3.2/tarlz4.go.lz4	2020-09-28 10:43:21.000000000 +0200
+++ archiver-3.3.2/tarlz4.go	2020-10-05 13:06:17.578418304 +0200
@@ -5,7 +5,7 @@ import (
 	"io"
 	"strings"
 
-	"github.com/pierrec/lz4/v3"
+	"github.com/pierrec/lz4"
 )
 
 // TarLz4 facilitates lz4 compression
```
and build. Fedora package build process fails with the following errors:
```
_build/src/github.com/mholt/archiver/lz4.go:19:3: w.Header undefined (type *lz4.Writer has no field or method Header)
_build/src/github.com/mholt/archiver/tarlz4.go:87:7: lz4w.Header undefined (type *lz4.Writer has no field or method Header)
```

It looks like option handling and compression level setting got changed:
https://github.com/pierrec/lz4/compare/v3.3.2..v4.0.2

I have nearly zero Golang knowledge, but this crude patch makes it compile and `go test` passes:
``` diff
diff -up archiver-3.3.2/lz4.go.lz4 archiver-3.3.2/lz4.go
--- archiver-3.3.2/lz4.go.lz4	2020-09-28 10:43:21.000000000 +0200
+++ archiver-3.3.2/lz4.go	2020-10-05 13:28:21.581995885 +0200
@@ -5,7 +5,7 @@ import (
 	"io"
 	"path/filepath"
 
-	"github.com/pierrec/lz4/v3"
+	"github.com/pierrec/lz4"
 )
 
 // Lz4 facilitates LZ4 compression.
@@ -16,7 +16,12 @@ type Lz4 struct {
 // Compress reads in, compresses it, and writes it to out.
 func (lz *Lz4) Compress(in io.Reader, out io.Writer) error {
 	w := lz4.NewWriter(out)
-	w.Header.CompressionLevel = lz.CompressionLevel
+	options := []lz4.Option{
+		lz4.CompressionLevelOption(lz4.CompressionLevel(1 << (8 + lz.CompressionLevel))),
+	}
+	if err := w.Apply(options...); err != nil {
+		return err
+	}
 	defer w.Close()
 	_, err := io.Copy(w, in)
 	return err
diff -up archiver-3.3.2/tarlz4.go.lz4 archiver-3.3.2/tarlz4.go
--- archiver-3.3.2/tarlz4.go.lz4	2020-09-28 10:43:21.000000000 +0200
+++ archiver-3.3.2/tarlz4.go	2020-10-05 13:28:21.581995885 +0200
@@ -5,7 +5,7 @@ import (
 	"io"
 	"strings"
 
-	"github.com/pierrec/lz4/v3"
+	"github.com/pierrec/lz4"
 )
 
 // TarLz4 facilitates lz4 compression
@@ -84,7 +84,12 @@ func (tlz4 *TarLz4) wrapWriter() {
 	var lz4w *lz4.Writer
 	tlz4.Tar.writerWrapFn = func(w io.Writer) (io.Writer, error) {
 		lz4w = lz4.NewWriter(w)
-		lz4w.Header.CompressionLevel = tlz4.CompressionLevel
+		options := []lz4.Option{
+			lz4.CompressionLevelOption(lz4.CompressionLevel(1 << (8 + tlz4.CompressionLevel))),
+		}
+		if err := lz4w.Apply(options...); err != nil {
+			return lz4w, err
+		}
 		return lz4w, nil
 	}
 	tlz4.Tar.cleanupWrapFn = func() {
```

**Comment by coolaj86** [comment] 2020-10-08 01:26
@rathann Sorry, I didn't see this issue come in the other day. This looks great.

Would you submit this as a PR? If it passes the tests (which it looks like it will), then I'll get this merged in and cut a new release soon.

This is what you'll need to do:

1. Install `go`, if you don't have it. I recommend https://webinstall.dev/golang as the simplest, most lightweight way to do that.
2. Make the changes you've described above
3. Run the go tooling from the cloned directory:
    ```bash
    # Make the change as described above
    go fmt ./...
    go mod tidy
    ```
4. Push all of the changes

**Comment by rathann** [comment] 2020-10-26 09:28
@coolaj86 Sorry, I didn't have time to work on this earlier. Are you sure you want me to commit the result of `go mod tidy`? It removes all dependencies marked with `// indirect` from `go.mod` and `go.sum`.

**Comment by coolaj86** [comment] 2020-10-26 22:02
@rathann You'll notice that the current patch is failing due to `go mod tidy` not having been run.

Realistically though, I don't think anyone should be using the version of Go that comes packaged with a distribution. It's bound to be out of date and to not follow the normal rules. The _real_ solution to this problem is to use the official version of Go. [Webi](https://webinstall.dev/golang) installs the official Go from https://golang.org/dl/ cleanly, as non-root, and with the correct `PATH` set up.

Does updating lz4 break any of the `archiver`'s API compatibilities, or is it just internal implementation? If it does I could create a provisional `v4` branch, but I don't think we could merge it into `v3`.

**Comment by rathann** [comment] 2020-10-27 21:46
> @rathann You'll notice that the current patch is failing due to `go mod tidy` not having been run.

Fixed.

> Realistically though, I don't think anyone should be using the version of Go that comes packaged with a distribution. It's bound to be out of date and to not follow the normal rules. The _real_ solution to this problem is to use the official version of Go. [Webi](https://webinstall.dev/golang) installs the official Go from https://golang.org/dl/ cleanly, as non-root, and with the correct `PATH` set up.

No idea about that, I don't even know Go. I used distro-included Go and it seems to work:
```
$ go version
go version go1.14.9 linux/amd64
```

> Does updating lz4 break any of the `archiver`'s API compatibilities, or is it just internal implementation?

I don't know. How do I check that?

> If it does I could create a provisional `v4.x` branch, but I don't think we could merge it into `v3`.

It's your call. I'm just a distro package maintainer who wanted to package one thing and ended up with maintaining all its Go dependencies.

**Comment by coolaj86** [comment] 2020-10-28 01:22
> I used distro-included Go and it seems to work

But then why are you having to change archiver's dependencies?

> lz4 was updated to 4.0.2 in Fedora rawhide

This is what raises alarm bells, which I overlooked at first.

Go is a _statically_ compiled language and dependencies are managed via `go mod` and `git` (at least in the mainline distribution, from the Golang authors). Nothing about how `lz4` is packaged in Fedora should have any effect on how `archiver` is packaged.

Go does have _experimental_ dynamically loaded modules, but this was intended for loading new features at runtime without recompiling the binary - a very niche use case.

Taking a step back:

Which package are you in charge of and how is it dependent on archiver? Could you give me a link to the git repo and specifically point out the build script? We can probably make a small change to that process so that it creates a standard Go binary using the standard Go tooling (if that's desirable).

**Comment by rathann** [comment] 2020-10-28 08:11
> > I used distro-included Go and it seems to work
> 
> But then why are you having to change archiver's dependencies?

Because it's failing to build against the new `lz4`.

> > lz4 was updated to 4.0.2 in Fedora rawhide
> 
> This is what raises alarm bells, which I overlooked at first.
> 
> Go is a _statically_ compiled language and dependencies are managed via `go mod` and `git` (at least in the mainline distribution, from the Golang authors). Nothing about how `lz4` is packaged in Fedora should have any effect on how `archiver` is packaged.

I know it has been statically compiled so far and this hasn't changed in Fedora. The issue is build dependencies (as obviously there are no runtime dependencies with static linking).

> Go does have _experimental_ dynamically loaded modules, but this was intended for loading new features at runtime without recompiling the binary - a very niche use case.

I know and Fedora Golang community is looking forward to this feature as it'll enable the desired packaging standard and let us release security and other bug fixes without recompiling every dependent Go package.

> Taking a step back:
> 
> Which package are you in charge of and how is it dependent on archiver?

I maintain `archiver`. It depends on `lz4` at build time, so when `lz4` maintainer updated it to an incompatible version, I was affected the next time I tried to rebuild `archiver`.

> Could you give me a link to the git repo and specifically point out the build script? We can probably make a small change to that process so that it creates a standard Go binary using the standard Go tooling (if that's desirable).

I can of course give you the link to the git repo of the [package](https://src.fedoraproject.org/rpms/golang-github-mholt-archiver). Fedora **is** open source. However, using upstream build process unmodified is not an option as it requires network access, which is disabled on the build system for security and reproducibility reasons. What the build process does is pre-install all the build dependencies into `$GOROOT` so that `go build` can find them without downloading anything.

**Comment by coolaj86** [comment] 2020-10-30 03:18
> What the build process does is pre-install all the build dependencies into $GOROOT so that go build can find them without downloading anything.

`$GOROOT` is deprecated. Should be using `go mod` since go1.11.

For that sort of build process everything should be installed into a `vendor` folder in the package root and then should be built with `go build -mod=vendor`.

(cc/ @mholt this issue is a strong case for `go mod vendor`, IMO)

> I know and Fedora Golang community is looking forward to this feature as it'll enable the desired packaging standard and let us release security and other bug fixes without recompiling every dependent Go package.

Well, that just makes me sad.

It defeats Go's inherent packaging and security practices. Go is not C and trying to treat Go like C will only lead to frustration and sadness.

In practice I'd say it's much more likely that someone DOES NOT update their system because of all the shared dependencies breaking things and to have something self contained is a better deal. That's more of a religious debate than something to solve here, but I _hate_ shared libraries (and hence I love Go). I literally [pick tools](https://webinstall.dev/) that are built and distributed statically because I know that I can update them without putting the rest of my system at risk of breaking.

Anyway, I think that this change can go in as v3.x without any breaking changes. I'll see if I can merge and publish momentarily. :D

**Closed** 2020-10-30 03:27 UTC
Labels: feature request

**Comment by mholt** [comment] 2020-10-30 18:13
Vendoring dependencies is not something I'm willing to consider, as we did it with Caddy and it was a mess to manage and made the repo unbearably heavy for common, simple tasks. It also introduced bugs! That was fun.

I know one of the Fedora package maintainers and they're often more reasonable than Debian's ecosystem, but I'm not really sure I understand the problem here?

```diff
-	"github.com/pierrec/lz4/v3"
+	"github.com/pierrec/lz4"
```

^ This is not v4, that should be at `github.com/pierrec/lz4/v4`, so it makes sense that the v1 version doesn't have those fields...

If there is still a problem, can someone summarize it succinctly? :sweat_smile:

**Comment by coolaj86** [comment] 2020-10-30 18:30
@mholt The Fedora repos don't use the standard Go tooling. They have their own custom dependency management system designed to emulates how C libraries work, which ignores go.mod.

Upgrading to `"github.com/pierrec/lz4/v4"` did not cause any of archiver's APIs to break, so I merged it in.

**Comment by rathann** [comment] 2020-10-30 21:56
@coolaj86 I'm not sure what you understood from my poorly informed description of Fedora Go packaging, but we do allow parallel installation of different major versions of Go packages. As far as I know the only custom thing is disabling automated code downloads during the build process. `go.mod` is not ignored.

@mholt The import path in the final patch is exactly as you proposed. Thanks for your kind words about Fedora packagers. Being on friendly terms with our upstreams is one of Fedora core values.

**Comment by mholt** [comment] 2020-10-30 22:28
The packagers and developers do tug at each other quite often in my experience, but we can figure it out and make it work... usually ;)

**Comment by coolaj86** [comment] 2020-11-02 21:41
@rathann Just checking in: is everything working for you?

(friendliness may not one of my core values, but getting results is 👍 )

**Comment by rathann** [comment] 2020-11-02 22:09
@coolaj86 Yes, I've just built archiver 3.5.0 for Fedora 33 and development branch on all our arches and the tests pass. Thanks!
