### ISSUE TITLE
Improve command help text

### ISSUE THREAD

**Issue by philippgille** [mholt/archiver#163] opened 2019-04-26 11:46 UTC
## What would you like to have changed?

I would like to get a more descriptive help text when using `archiver` as command (as `arc` in a terminal).

The current (just updated with `get get -u`) help text starts like this:

```
Usage: arc {archive|unarchive|extract|ls|compress|decompress|help} [arguments...]
  archive
    Create a new archive file. List the files/folders
    to include in the archive; at least one required.
```

From this info you still don't know how to archive a file or folder. From the text you might think that you can use `arc archive file-to-archive`, because that's `arc` and the subcommand and as `[arguments...]` you enter what the archive info tells you: "list the files [...]; at least one required", which is fulfilled. But it doesn't work that way. You get:

> format unrecognized by filename: file-to-archive

So the help should somehow make clear that the first argument *must* be the *target archive file*.

But that's not the only thing. There's the global flag `level`:

```
   -level int
    	Compression level (default -1)
```

But what compression levels are supported?  Only when entering an unsupported level (e.g. `10`), you get this:

```
2019/04/26 13:36:55 [ERROR] Walking file-to-archive: file-to-archive: writing: file-to-archive: making header: flate: invalid compression level 10: want value in range [-2, 9]
```

When using `arc` as command, this error should probably be a *message to the user*, instead of a *log entry*. Like: "You passed an invalid compression level (10). Supported levels: [-2, 9]" or something like that. But maybe that's a different issue and we should focus on the help text in this one. So at least the valid levels should already be shown in the help text.

If you don't want to make the help text too long, make `help` support the subcommands. So `arc help` prints an overview and mentions you can use help on subcommands, then `arc help archive` gives you more info on how to use that, including the mandatory output file as parameter, as well as the compression level. This is intuitive and people will know this pattern from commands like `docker help run`, `git help push` etc.

## Why is this feature a useful, necessary, and/or important addition to this project?

I think a great advantage of `arc` is its *usability* and *ease of use*, which is great compared to remembering all the flags of `tar` for example, but without a proper help text this hurts exactly this advantage.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

You can figure out how `arc` works by some common sense and some trial and error until the help text is improved.

## Please link to any relevant issues, pull requests, or other discussions.

/

**Comment by stoerr** [comment] 2020-07-06 09:18
I'd like to heavily support that. Besides that it is not clear which options apply to which commands, it is not clear to me how one could switch an option off (many of them say default true). Also there are some strange behaviours of the commands which aren't mentioned in the help, and I don't know whether I'm doing something wrong or there is much functionality missing:
- if I unpack an archive it creates a directory named like the archive in the current directory - even if I explicitly give a . as directory to unpack
- I couldn't find any way to create an archive containing files with arbitrary paths, e.g. a/b/c.txt, a/b/d.txt etc.  - the directory a/ seems thrown away.

**Comment by mholt** [comment] 2020-07-06 17:45
I agree, the CLI could use some attention.

Unfortunately I've been swamped with my day job (especially busy since all the craziness this year, for some reason). Would be happy to have help maintaining this repo in the meantime.

**Comment by sergeevabc** [comment] 2021-04-18 13:02
Actually, I am here, because of the confusion caused by vague help message.
Where should I put `-level` in the following sequence to squeeze extra bytes and what levels are possible for `zip`?
``` console
$ arc.exe archive test.zip "my folder"
```

**Comment by mholt** [comment] 2022-01-26 16:35
As I don't have plans/time to make a command for v4 (unless sponsorships motivate it specifically), I'll close this issue; but I've labeled it with "command" so we can remember this if someone does end up contributing a command later. Thanks!

**Closed by mholt** 2022-01-26 16:35 UTC
Labels: feature request, command
